version: '3'

services:

  # frontend:
  #   image: ghcr.io/argadepp/bachatgat:master
  #   environment:
  #     - DB_HOST=database
  #     - DB_USER=root
  #     - DB_PASSWORD=password
  #     - DB_NAME=jansevadb    
  #   ports:
  #     - "80:5000"

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: jansevadb
    ports:
      - "3306:3306"
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d      
