version: '3'

services:

  frontend:
    build:
      context: .
    ports:
      - "80:5000"

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: jansevadb
    ports:
      - "3306:3306"
