version: '3'

services:
  # backend:
  #   build:
  #     context: ./backend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - database

  frontend:
    build:
      context: .
    ports:
      - "80:80"

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: jansevadb
    ports:
      - "3306:3306"
