version: '3'

services:

  frontend:
    build:
      context: .
    environment:
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=jansevadb    
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
      # - ./conf:/etc/apache2/sites-available
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: jansevadb
    ports:
      - "3306:3306"
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d      